const path=require("path")
module.exports={
    devServer:{//配置正向代理
        proxy:{
            "/api":{
                target:"https://api1.34580.com",
                "changeOrigin":true,
                "pathRewrite":{
                    "^/api":""
                }
            }
        }
    },
    configureWebpack:{
        resolve:{
            alias:{
                "@":path.join(__dirname,"./src"),
                "api":path.join(__dirname,"./src/api"),
                "assets":path.join(__dirname,"./src/assets"),
                "lib":path.join(__dirname,"./src/lib"),
                "components":path.join(__dirname,"./src/components"),
                "views":path.join(__dirname,"./src/views"),
                "common":path.join(__dirname,"./src/common"),
                "utils":path.join(__dirname,"./src/utils"),
                "router":path.join(__dirname,"./src/router"),
                "store":path.join(__dirname,"./src/store")
            }
        }
    }
}